### PR TITLE
Phase 3: Slack commenting

### PR DESCRIPTION
**Pull request by belucid**
https://trello.com/c/AgWsLd0i

This PR integrates our comments with Slack. OC comments are mirrored to Slack, and Slack comments in the thread are mirrored back to OC. It accounts for the following scenarios from the comment design doc:

- [x] OC User sends first comment of an entry (necessarily in-app)
- [x] OC User sends subsequent comment in-app
- [x] OC User sends a subsequent threaded reply in Slack thread
- [x] Slack only users sends threaded reply in Slack (no OC user for them yet)

- [x] Same OC User, different tab, is on topic view when a first ever comment comes in
- [x] Same OC User, different tab, is in comment view when a first ever comment comes in

- [x] Another OC User is on topic view when a first ever comment comes in
- [x] Another OC User is in comment view when a first ever comment comes in

- [x] Same OC User, different tab, is on topic view when a first ever comment comes in from OC
- [x] Same OC User, different tab, is on topic view when a subsequent comment comes in from OC

- [x] Another OC User is on topic view when a first ever comment comes in from OC
- [x] Another OC User is on topic view when a subsequent comment comes in from OC

- [x] Same OC User, different tab, is in comment view when a first ever comment comes in
- [x] Same OC User, different tab, is in comment view when a subsequent comment comes in

- [x] Another OC User is in comment view when a first ever comment comes in
- [x] Another OC User is in comment view when a subsequent comment comes in

To test, run through the scenarios above using the mainline web, phase 3 API and mainline auth.

NB: we don't yet have channel selection for mirroring target, so all comments are hard coded to mirror to OC's own `bot-testing` channel. This is temporary of course.

NB: You'll need to configure ngrok and Slack to point at your local development. Follow the instructions in the README.

NB: Comments coming in from Slack are anonymous at this point. This will be addressed in follow on card: https://trello.com/c/rjjcRKFY

NB: message.channel event hook has been setup for localhost app (currently disabled, enable/disable as needed) and for demo.carrot.io, but not for staging.carrot.io as this branch hasn't been running there yet.

Review the code.

NB: After merging, update the 2 SVG image URLs in the README from this branch `phase3` to branch `mainline`.

These supporting PRs need reviewed:

https://github.com/open-company/open-company-lib/pull/12

https://github.com/open-company/open-company-api/pull/82

https://github.com/open-company/open-company-bot/pull/16

### CODE REVIEW

**Comment by belucid** [comment]
Ignore the version-eye check failure @bago2k4 
 
It's because you put out a new oc.lib on a different branch.

**Review by bago2k4 — CHANGES_REQUESTED** [review]
This scenario looks like is a failing one.
I created an OC user via Slack. Then added a first comment to a topic.
I then invited a new user (first as viewer then changed to admin). With this last user i opened the topic and i have send another message to that same thread we all partecipated to.
I got this:
```
Input to ->comment does not match schema: 

	 [0;33m  [nil (named {:name (not (oc.lib.schema/fn--33676 ""))} user)] [0m 
```

here are the request details

```
Request URL:http://localhost:3002/orgs/aac6-4ea3-9f3e/boards/5d98-433e-868e/topics/product/entries/4d87-4b48-87db/comments/
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:[::1]:3002
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://localhost:3559
Access-Control-Expose-Headers:Vary, X-Liberator-Trace-Id, Link, X-Liberator-Trace
Content-Length:124
Content-Type:text/plain;charset=utf-8
Date:Tue, 13 Jun 2017 18:09:57 GMT
Link:<//x-liberator/requests/n5zbz>; rel=x-liberator-trace
Server:http-kit
Vary:Accept
X-Liberator-Trace::decision (:encoding-available? {:representation {:encoding "identity"}})
X-Liberator-Trace::decision (:known-content-type? true)
X-Liberator-Trace::decision (:valid-entity-length? true)
X-Liberator-Trace::decision (:is-options? false)
X-Liberator-Trace::decision (:accept-exists? true)
X-Liberator-Trace::decision (:media-type-available? {:representation {:media-type "application/vnd.open-company.comment.v1+json"}})
X-Liberator-Trace::decision (:initialize-context {:jwtoken "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlhY29wbysxM2p1bkBvcGVuY29tcGFueS5jb20iLCJyZWZyZXNoLXVybCI6Imh0dHA6XC9cL2xvY2FsaG9zdDozMDAzXC91c2Vyc1wvcmVmcmVzaCIsImxhc3QtbmFtZSI6IiIsImFkbWluIjpbIjFkOTUtNGI1Yi04NDVjIl0sIm5hbWUiOiIiLCJhdmF0YXItdXJsIjoiIiwiZXhwaXJlIjoxNDk3Mzg0MzMyMTE2LCJ1c2VyLWlkIjoiMmQ5Yy00ZTY3LWI4YTciLCJmaXJzdC1uYW1lIjoiIiwidGVhbXMiOlsiMWQ5NS00YjViLTg0NWMiXSwiYXV0aC1zb3VyY2UiOiJlbWFpbCIsInNsYWNrLWJvdHMiOnt9fQ.Z1UHJHn3w09J1iEEsU9JJhXLPlv8fbGsec3YftDhGhQ", :user {:email "iacopo+13jun@opencompany.com", :refresh-url "http://localhost:3003/users/refresh", :last-name "", :admin ["1d95-4b5b-845c"], :name "", :avatar-url "", :expire 1497384332116, :user-id "2d9c-4e67-b8a7", :first-name "", :teams ["1d95-4b5b-845c"], :auth-source "email", :slack-bots {}}})
X-Liberator-Trace::decision (:language-available? true)
X-Liberator-Trace::decision (:accept-charset-exists? nil)
X-Liberator-Trace::decision (:accept-encoding-exists? "gzip, deflate, br")
X-Liberator-Trace::decision (:valid-content-header? true)
X-Liberator-Trace::decision (:processable? [false {:reason "Input to ->comment does not match schema: \n\n\t [0;33m  [nil (named {:name (not (oc.lib.schema/fn--33676 \"\"))} user)] [0m \n\n"}])
X-Liberator-Trace::handler (:handle-unprocessable-entity)
X-Liberator-Trace::decision (:allowed? true)
X-Liberator-Trace::decision (:authorized? {:email "iacopo+13jun@opencompany.com", :refresh-url "http://localhost:3003/users/refresh", :last-name "", :admin ["1d95-4b5b-845c"], :name "", :avatar-url "", :expire 1497384332116, :user-id "2d9c-4e67-b8a7", :first-name "", :teams ["1d95-4b5b-845c"], :auth-source "email", :slack-bots {}})
X-Liberator-Trace::decision (:malformed? [false {:data {:body "Another OC user"}}])
X-Liberator-Trace::decision (:method-allowed? :post)
X-Liberator-Trace::decision (:uri-too-long? false)
X-Liberator-Trace::decision (:service-available? true)
X-Liberator-Trace::decision (:known-method? :post)
X-Liberator-Trace::decision (:accept-language-exists? "en-US,en;q=0.8,it;q=0.6")
X-Liberator-Trace-Id:n5zbz
Request Headers
view source
Accept:application/vnd.open-company.comment.v1+json
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8,it;q=0.6
Access-Control-Allow-Headers:Content-Type, Authorization
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImlhY29wbysxM2p1bkBvcGVuY29tcGFueS5jb20iLCJyZWZyZXNoLXVybCI6Imh0dHA6XC9cL2xvY2FsaG9zdDozMDAzXC91c2Vyc1wvcmVmcmVzaCIsImxhc3QtbmFtZSI6IiIsImFkbWluIjpbIjFkOTUtNGI1Yi04NDVjIl0sIm5hbWUiOiIiLCJhdmF0YXItdXJsIjoiIiwiZXhwaXJlIjoxNDk3Mzg0MzMyMTE2LCJ1c2VyLWlkIjoiMmQ5Yy00ZTY3LWI4YTciLCJmaXJzdC1uYW1lIjoiIiwidGVhbXMiOlsiMWQ5NS00YjViLTg0NWMiXSwiYXV0aC1zb3VyY2UiOiJlbWFpbCIsInNsYWNrLWJvdHMiOnt9fQ.Z1UHJHn3w09J1iEEsU9JJhXLPlv8fbGsec3YftDhGhQ
Cache-Control:no-cache
Connection:keep-alive
Content-Length:26
Content-Type:application/vnd.open-company.comment.v1+json
Host:localhost:3002
Origin:http://localhost:3559
Pragma:no-cache
Referer:http://localhost:3559/opencompany/who-we-are/product
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Request Payload
view source
{body: "Another OC user"}
body
:
"Another OC user"
Name
```

**Comment by bago2k4** [comment]
also tests are failing, it looks like `gniazdo` dependency has a unknown license..

**Comment by belucid** [comment]
The not in thread problem is resolved. You're resolving the no name JWT problem.

**Comment by belucid** [comment]
@bago2k4 NB: there is now a bot branch in this PR too.

**Review by bago2k4 — APPROVED** [review]

**Pull request merged**
